### ISSUE TITLE
Galaxy A3 (2017)

### ISSUE THREAD

**Issue by winne42** [jaredrummler/AndroidDeviceNames#11]
Great library! Samsung Galaxy A3 (both old and 2017) seems to missing completely, my A3 (2017) lists as 

Build.DEVICE="a3y17lte"
Build.MODEL="SM-A320FL"

Regards, winne42

**Comment by jaredrummler** [comment]
It isn't included in the "popular" device list. If you want it included you can modify [POPULAR.json](https://github.com/jaredrummler/AndroidDeviceNames/blob/master/POPULAR.json) and create a pull request.

This should also work:

```java
DeviceName.with(context)
    .setModel("SM-A320FL")
    .setCodename("a3y17lte")
    .request(new DeviceName.Callback() {

  @Override public void onFinished(DeviceName.DeviceInfo info, Exception error) {
    String name = info.marketName;            // "Galaxy A3(2017)"
    // FYI: We are on the UI thread.
  }
});
```

![screen](https://user-images.githubusercontent.com/6203389/31797847-51104698-b4e5-11e7-92ab-659a339237b8.png)
