### ISSUE TITLE
Add option to opt-out of web request

### ISSUE THREAD

**Issue by tir38** [jaredrummler/AndroidDeviceNames#13]
Some apps might not be comfortable sending a web request (especially using HttpUrlConnection) with device name for every user (minus the 600 most popular phones). There are security and performance reasons to want to turn this off.

**Comment by jaredrummler** [comment]
Just use `DeviceName.getDeviceName()` and it won't send a web request. This handles the most popular devices. 

I am also considering including a database with all device names but I don't want to bloat the library.
