### ISSUE TITLE
Model data is less than Google Support Devices

### ISSUE THREAD

**Issue by qtfreet00** [jaredrummler/AndroidDeviceNames#21]
I download the support devices pdf at https://support.google.com/googleplay/answer/1727131?hl=en

my android phone model is Huawei p20 pro

I found it in this pdf ,  

Huawei P20 Pro HWCLT CLT-AL00

in your datebase, i cant found this model, thx😄

**Comment by ibuprophen1** [comment]
Based upon the following link... 

https://www.gsmchoice.com/en/catalogue/huawei/p20pro/

... The Huawei P20 Pro is aka "CLT-L04, CLT-L09, CLT-L09C, CLT-L29, CLT-L29C, CLT-AL00 & CLT-AL01". 

Isn't that weird! 😵


~Ibuprophen
