### ISSUE TITLE
Cant compile project after implementing this library

### ISSUE THREAD

**Issue by MakawaMT** [jaredrummler/AndroidDeviceNames#25]
I'm getting all sorts of errors when I implement the library and try to compile, the gradle is failing to compile at all times.
Has anyone else faced this?

**Comment by MakawaMT** [comment]
More than one file was found with OS independent path 'META-INF/proguard/androidx-annotations.pro' is part of the error messages im receiving.

**Comment by TheHollidayInn** [comment]
I'm getting the same issue.

**Comment by TheHollidayInn** [comment]
I fixed it by adding this to my app build file
```
packagingOptions {
       pickFirst   'META-INF/proguard/androidx-annotations.pro'
 }
```

**Comment by MakawaMT** [comment]
@TheHollidayInn thanks...adding that to my build.gradle inside the android tag worked and didnt cause any errors.
