### ISSUE TITLE
Update frequency

### ISSUE THREAD

**Issue by matrixyf** [jaredrummler/AndroidDeviceNames#44]
Hi, I read the source code and noticed that the device info is retrieved from the inner database of assets, who is taking care of the update of database and how often it does?
Another question, do this library have an mechanism to update the device list from network?

**Comment by ytheekshana** [comment]
Read the README.md again

**Comment by sanchezzzhak** [comment]
> The above code queries a database included in the library based on Google's maintained list . This supports over 27,000 devices. 

a link to the document can be found in the [README.md](https://github.com/jaredrummler/AndroidDeviceNames/blob/master/README.md)
