### ISSUE TITLE
Database update (Jan 2021)

### ISSUE THREAD

**Issue by NotNotMarshall** [jaredrummler/AndroidDeviceNames#47]
It has been quite long that you haven't updated the database so I just did it in my fork, you can download the 2 files from down here:

https://github.com/NotNotMarshall/AndroidDeviceNames/tree/master/database

More than 3 thousand devices were added since Mar 2020 (last update of this library).

@jaredrummler

**Comment by NotNotMarshall** [comment]
@jaredsburrows

**Comment by jaredsburrows** [comment]
Why not make a PR?

**Comment by NotNotMarshall** [comment]
> Why not make a PR?

@jaredsburrows 
Read this comment:
https://github.com/jaredrummler/AndroidDeviceNames/issues/43#issuecomment-757908060

**Comment by NotNotMarshall** [comment]
> Why not make a PR?

You seems so fucking retarded

**Comment by NotNotMarshall** [comment]
> Why not make a PR?

@jaredsburrows 
you fucking retarded or something? 
https://github.com/jaredrummler/AndroidDeviceNames/issues/43#issuecomment-757908060

**Comment by tdtran** [comment]
@jaredrummler seems like a someone does not know what a PR is

**Comment by NotNotMarshall** [comment]
> Looks like someone does not know what a PR is

@tdtran Follow the comment reference you turd! I've already told him the fucking reason why I can't PR, otherwise I'd be PRing it up your crack

**Comment by ytheekshana** [comment]
could any one update the database please

**Comment by mattmapadmi** [comment]
@NotNotMarshall 

Press this button chucklenuts

![image](https://user-images.githubusercontent.com/40175381/104767344-dc0ab480-5763-11eb-8d5a-1edec4a220fd.png)

**Comment by NotNotMarshall** [comment]
> @NotNotMarshall
> 
> Press this button chucklenuts
> 
> ![image](https://user-images.githubusercontent.com/40175381/104767344-dc0ab480-5763-11eb-8d5a-1edec4a220fd.png)

NO!
F*** NO! I won't push it! F***ing developers should bother their f***ing lazy bums to update their lib.
I will NOT do their job.
If you want a fresh up to date database then import my fork otherwise have a nice life!

**Comment by xcarpentier** [comment]
I create a PR #51 for this, please let me know if it's ok or if I miss something.
