### ISSUE TITLE
How can we manually update the Database

### ISSUE THREAD

**Issue by ytheekshana** [jaredrummler/AndroidDeviceNames#48]
How can we manually update the Database, android-devices.db & android-devices.zip files. I want to exclude the devices lower than android 6.0. So i can decrease the library size.

**Comment by ytheekshana** [comment]
@NotNotMarshall

**Comment by NotNotMarshall** [comment]
@ytheekshana Yo!

**Comment by ytheekshana** [comment]
Implemented my own db. Now I am not using this.
