### ISSUE TITLE
Result of known devices should include manufacturer

### ISSUE THREAD

**Issue by skolarianer** [jaredrummler/AndroidDeviceNames#5]
The results (fallback) of unknown devices contain the manufacturer. The results of known devices mostly don't include the manufacturer.

**Comment by jaredrummler** [comment]
Will you please provide an example?

**Comment by skolarianer** [comment]
E.g. result for 1. Generation Motorola Moto G is just `Moto G (1st Gen)`.

**Comment by jaredrummler** [comment]
Please provide an example with code.

**Comment by skolarianer** [comment]
I simply call `DeviceName.getDeviceName()`.

Result of `Log.d("Device name", DeviceName.getDeviceName());` is
D/Device name: Moto G (1st Gen)

**Comment by jaredrummler** [comment]
You can get the manufacturer using [Build.MANUFACTURER](https://developer.android.com/reference/android/os/Build.html#MANUFACTURER) and add that as a prefix to the device name.

```java
String name = Build.MANUFACTURER + " " + DeviceName.getDeviceName();
```

 I think this is working as intended. The name of the device comes from Google's list, so I won't be changing anything here.

You can also use the following method to get the manufacturer of other device names:

```java
DeviceName.with(context).setCodename("XT1028").request(new DeviceName.Callback() {

  @Override public void onFinished(DeviceName.DeviceInfo info, Exception error) {
    String manufacturer = info.manufacturer;  // "Motorola"
    String name = info.marketName;            // "Moto G (1st Gen)"
    String model = info.model;                // "XT1028"
  }
});
```

**Comment by skolarianer** [comment]
If I just concatenate the string the manufacturer is doubled for unknown devices.

For unknown devices you are checking if `Build.MODEL` contains the manufacturer:
```
  public static String getDeviceName() {
    String manufacturer = Build.MANUFACTURER;
    String model = Build.MODEL;
    String fallback;
    if (model.startsWith(manufacturer)) {
      fallback = capitalize(model);
    } else {
      fallback = capitalize(manufacturer) + " " + model;
    }
    return getDeviceName(Build.DEVICE, model, fallback);
  }
```

Why not do the same for the top 600 devices? At the moment I use the following code to solve this but for consistency I think it's worth considering to implement this in your library.

```
String manufacturer = capitalize(Build.MANUFACTURER);
String devName = DeviceName.getDeviceName();
    if ( !devName.startsWith(manufacturer)) {
        devName = manufacturer + " " + devName;
    }
```

**Comment by jaredrummler** [comment]
For consistency, I removed the manufacturer from the fallback name instead of adding it for each device.
