### ISSUE TITLE
Return wrong MODEL

### ISSUE THREAD

**Issue by cuong-hovit** [jaredrummler/AndroidDeviceNames#6]
My Android device is Samsung Galaxy J7 with MODEL = SM-J710FN. Its default device name is Galaxy J7 (2016). However, DeviceName.getDeviceName() API returns SM-J710F. Thanks!

**Comment by jaredrummler** [comment]
That device model is the Galaxy On8 according to Google's maintained list. You can use the following code to get device info:

```java
String codename = "j7xlte"; // Build.DEVICE
String model = "SM-J710FN"; // Build.MODEL

DeviceName.with(this).setCodename(codename).setModel(model).request(new DeviceName.Callback() {

  @Override public void onFinished(DeviceName.DeviceInfo info, Exception error) {
    String name = info.getName(); // Galaxy On8
  }
});
```
