### ISSUE TITLE
New way to obtain marketName

### ISSUE THREAD

**Issue by dagonco** [jaredrummler/AndroidDeviceNames#60]
Because it seems that this repository has not had changes for 1 year and every day there are surely new devices that are not covered by the database of this library.

I have created a [library](https://github.com/dagonco/GoogleSupportedDevices) that is able to retrieve the marketName of the device without having to update the database, directly from the Google's csv file, in case it is registered.

I'm not here to advertise, but maybe more than one person can help you.
Sorry for the disturb.

**Comment by ldavidsp** [comment]
@dagonco Thank you for share, I was find new solutions.
