### ISSUE TITLE
Note 3 Missing

### ISSUE THREAD

**Issue by akhilc1** [jaredrummler/AndroidDeviceNames#8]
Hi device name for Samsung Note 3 is missing (Note 3 Model number is "SM-N900", Codename is "ha3g")

if (codename != null && codename.equals("ha3g") || model.equals("SM-N900")
                || model.equals("SM-N9005")
                || model.equals("SM-N9002")
                || model.equals("SM-N9005T")
                || model.equals("SM-N9005P")
                || model.equals("SM-N9005A")
                || model.equals("SM-N9007")
                || model.equals("SM-N900W8")
                || model.equals("SM-N9000Q")
                || model.equals("SM-N9000")
                || model.equals("SM-N900X")
                || model.equals("SM-N9000Q_MEA")
                || model.equals("SM-N900W8_LA")
                || model.equals("SM-N900_MEA")
                || model.equals("SM-N900_SEA")
                || model.equals("SM-N900_SWA")
                || model.contains("SM-N9008V")
                || model.contains("SM-N900K")
                || model.contains("SM-N900L")
                || model.contains("SM-N900S")) {
            return "Galaxy Note 3";
        }

Got device models from: https://forum.xda-developers.com/showthread.php?t=2471434

**Comment by jaredrummler** [comment]
I don't consider it a popular device so it isn't included. You can still get the device name using the callback:

```java
    DeviceName.with(appContext).setModel("SM-N900").request(new DeviceName.Callback() {
      @Override public void onFinished(DeviceName.DeviceInfo info, Exception error) {
        String name = info.getName();
      }
    });
```
